### ISSUE TITLE
Headers in XMLHttpRequest sometimes come duplicated

### ISSUE THREAD

**Issue by kakai248** [p7s1digital/oasis-jsbridge-android#44]
Hey!

I've been playing around with the library and hit a very weird issue. I noticed that some requests were failing because headers were being duplicated.

Example:
Given an header `a` with the value `1`, instead of sending `a: 1`, it would send `a: 1,1`

Now, this is very rare and very hard to reproduce. There's no particular thing I was doing on the few occasions that I was able to see it. Just navigating through the app and doing network requests.

I tried logging the JS side to see if the headers were being set multiple times there:
```javascript
XMLHttpRequest.prototype.setRequestHeader = function(header, value) {
  console.log("setting header: " + header + " - " + value);
  this._requestHeaders.push([header, value]);
};
```

But they were not. Everything was fine. But once I received the headers on the native side, and I could see this in the `Timber.v("javaSend($httpMethod, $url, $headers)")` logging, they would be duplicated. Using the example from before:

JS would log:
```
setting header: a - 1
```

Native would log:
```
javaSend(GET, http://some.url, [["a", "1"], ["a", "1"]])
```

So this seems to be bridge related but I couldn't really pinpoint what was the cause. Maybe something related with arrays being passed over the bridge?

I know this is very little information to try and fix the issue, but I was wondering if you already caught some similar situation or have any idea what could it be.

In the mean time I'm fixing the problem with an interceptor that removes duplicated headers if both key and value match.

Thanks!

**Comment by kakai248** [comment]
I finally found out what the issue was. I'm using a JS lib that is an abstraction on top of XHR. Upon a timeout, it would retry the exact same request, ie. it didn't create a new XHR instance. It would call `open`, `setRequestHeader` and `send` again. Since `open` is not clearing the previously set request headers (according to spec it should: https://xhr.spec.whatwg.org/#the-open()-method), the headers would be getting duplicated.

Regarding the logs part, I was getting fooled by what I was seeing. It would print the JS log for every request header, but since this was for a different request, I missed it.

**Comment by bwalter** [comment]
Thanks for the detailed analysis. Now that #46 has been merged, is it fine for you if we close this issue?

**Comment by kakai248** [comment]
Already did. Bridge is looking quite stable!

Thank you!
