### ISSUE TITLE
setTimeout/setInterval is not execute correctly! 

### ISSUE THREAD

**Issue by mrtian** [p7s1digital/oasis-jsbridge-android#6]
No matter how long it is set, it is executed immediately!

**Comment by bwalter** [comment]
Thanks for the report. Please provide an example of how you are using it (JS code + ideally how you initialize the bridge and load the JS string).

**Comment by mrtian** [comment]
> Thanks for the report. Please provide an example of how you are using it (JS code + ideally how you initialize the bridge and load the JS string).


var _getReturnVal = function(resolve,reject){
        times+=1;
        if(times>=1000){
          reject("timeout");
        }else{
          if(Jfui.__message_return_val[msgId]){
            var _ret = Jfui.__message_return_val[msgId]["ret"]
            resolve(_ret);
            delete(Jfui.__message_return_val[msgId]);
          }else{
            setTimeout(function(){
              _getReturnVal(resolve,reject);
            },100);
          }
        }
      };

      this._postMessage(JSON.stringify(postData));

      return new Promise(_getReturnVal);

**Comment by mrtian** [comment]
I found it：

![image](https://user-images.githubusercontent.com/363241/86124224-56981d80-bb0d-11ea-8d7e-cc40779620c1.png)
javascript int to kotlin long error!

**Comment by bwalter** [comment]
Which version of the JS bridge are you using?

**Comment by mrtian** [comment]
> Which version of the JS bridge are you using?

0.9.68

**Comment by bwalter** [comment]
Please try again with the latest version, the conversion issue has been fixed since 0.9.68.

**Comment by mrtian** [comment]
> Please try again with the latest version, the conversion issue has been fixed since 0.9.68.

the latest version always show error:
config type error!

jsBridge = JsBridge();


or?
var jsBridgeConfig = JsBridgeConfig()
jsBridge = JsBridge(jsBridgeConfig)

**Comment by bwalter** [comment]
You ccan initialize liked this:
```
val jsBridge = JsBridge(JsBridgeConfig.standardConfig())
```

**Comment by mrtian** [comment]
> You can initialize it like this:
> 
> ```
> val jsBridge = JsBridge(JsBridgeConfig.standardConfig())
> ```

the lasted version incompatible with older versions!

de.prosiebensat1digital.oasisjsbridge.JsException: ReferenceError: identifier 'window' undefined

**Comment by mrtian** [comment]
> You can initialize it like this:
> 
> ```
> val jsBridge = JsBridge(JsBridgeConfig.standardConfig())
> ```

I found it's not support " class a{...}  "

**Comment by bwalter** [comment]
> the lasted version incompatible with older versions!

Yes, API stability is planned for v1.0 (which is anyway going to be released soon).

> de.prosiebensat1digital.oasisjsbridge.JsException: ReferenceError: identifier 'window' undefined
`window` and `global` are no longer hard-coded in the bridge but setting them is easy:
```jsBridge.evaluateNoRetVal("var global = globalThis; var window = globalThis;")```

> then my js always error @ Fatal error: uncaught: 'string required, found undefined (stack index -1)
Please provide more information (JS code, full stacktrace).

>  found it's not support " class a{...} "
It is an ES6 feature. Which flavor are you using: duktape or quickjs? If you don't use babel to transform your ES6 code to ES5, you need to use the `quickjs` flavor.

**Comment by oleksandr-yefremov** [comment]
Original issue was fixed in v0.10.0.
There were changes in API between 0.9.68 and 0.10.0 (introducing `JsBridgeConfig` for more flexible configuration, move global polyfills out of constructor etc.) Readme has all the necessary details. 
Closing the ticket as resolved.
