### ISSUE TITLE
0.10.0 can not download in gradle

### ISSUE THREAD

**Issue by ironmanTony** [p7s1digital/oasis-jsbridge-android#7]
0.10.0 can not download in gradle
0.9.68 can be download

**Comment by bwalter** [comment]
How did you add the dependency in your gradle file? This should work:
```
implementation("de.prosiebensat1digital.oasis-jsbridge-android:oasis-jsbridge-duktape:0.10.0")
```
(we will also update the documentation to reflect the change)

**Comment by ironmanTony** [comment]
my dependency is
```
implementation 'com.github.abner.oasis-jsbridge-android:oasis-jsbridge-quickjs:0.9.68'
```

this is ok
```
implementation("de.prosiebensat1digital.oasis-jsbridge-android:oasis-jsbridge-duktape:0.10.0")
```

the quickJs flavor 0.10.0 can't be download `oasis-duktape-quickjs`

**Comment by oleksandr-yefremov** [comment]
This is the correct dependency name for quickjs flavour:
```
implementation "de.prosiebensat1digital:oasis-jsbridge-quickjs:$jsbridgeVersion"
```

Closing the ticket since solution was provided for both flavours.
